vim.o.number = true
vim.o.relativenumber = true
vim.o.termguicolors = true
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.wrap = false
vim.g.mapleader = " "
vim.o.scrolloff = 8  -- üst/alt boşluk bırak
vim.o.sidescrolloff = 8 -- yatay boşluk
vim.o.sidescroll = 1
vim.o.sidescrolloff = 5
--vim.o.hidden = true
